version: '1.0'

services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
      - DB_HOST=postgres
      - DB_NAME=localdb
      - DB_USERNAME=user
      - DB_PASSWORD=password
    volumes:
      - ./WebApplication1:/source/WebApplication1
    ports:
      - "5001:5000"
  postgres:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "user"
      POSTGRES_DB: "localdb"
networks:
  default:
    external: false
    name: default_network
