version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge

services:
  app:
    container_name: 'app'
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    environment:
      DB_CONNECTION_STRING: "Host=localhost;Port=5432;Database=postgres;Username=user;Password=password"
    volumes:
      - ./DotnetApi:/source/DotnetApi
    ports:
      - "5001:5000"
    networks:
      - dockerapi-dev

  pgdb:
    container_name: 'pgdb'
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "user"
      POSTGRES_DB: "postgres"
    networks:
      - dockerapi-dev
