version: '1.0'

networks:
  dockerapi-dev:
    driver: bridge

services:
  migrations:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
      - DB_HOST=db
      - DB_NAME=localdb
      - DB_USERNAME=user
      - DB_PASSWORD=password
    working_dir: /source/WebApplication1
    volumes:
      - ./WebApplication1/migrations:/source/WebApplication1/Migrations
    networks:
      - dockerapi-dev
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
      - DB_HOST=db
      - DB_NAME=localdb
      - DB_USERNAME=user
      - DB_PASSWORD=password
    volumes:
      - ./WebApplication1:/source/WebApplication1
    ports:
      - "5001:5000"
    networks:
      - dockerapi-dev
  db:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "user"
      POSTGRES_DB: "localdb"
    networks:
      - dockerapi-dev
