name: Fly Deploy
on: [push]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: cd DotnetApi && flyctl deploy -a connect-api
          with:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
